import { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import { Header } from '../components/Header/Header'
import { Nav } from '../components/Nav/Nav'
import Provider from '@/redux/Provider'
import { Initialized } from './init'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Provider>
        <Initialized>
          <body className={inter.className}>
            <div className='app_wrapper'>
              <Header />
              <Nav />
              <main className="main">
                {children}
              </main>
            </div>
          </body>
        </Initialized>
      </Provider>
    </html>
  )
}
