import { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import { Header } from '../components/Header/Header'
import { Nav } from '../components/Nav/Nav'
import Providers from '@/redux/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Header />
          <Nav />
          <main>
            {children}
          </main>
        </body>
      </Providers>
    </html>
  )
}
